### ISSUE TITLE
Elaborar Características da Plataforma

### ISSUE THREAD

**Issue by leticiaarj** [Interacao-Humano-Computador/2019.2-OLX#11]
Analisar as características da plataforma de vendas OLX.

**Comment by juniopereirab** [comment]
Essa issue foi concluída. 
As [características da plataforma](https://github.com/Interacao-Humano-Computador/2019.2-OLX/wiki/Caracter%C3%ADsticas-da-Plataforma) já estão dispostas na Wiki corretamente.
