### ISSUE TITLE
Refazer o protótipo de papel

### ISSUE THREAD

**Issue by juniopereirab** [Interacao-Humano-Computador/2019.2-OLX#18]
**Descrição da tarefa:**
Fazer uma nova versão do protótipo de papel, utilizando o que foi dado como feedback pelo professor.
Um protótipo manual e sem cores, com enfoque na tarefa e não na interface.

**Tarefas:**
- [x] Fazer o protótipo de papel corretamente.
- [x] Atualizar todos os documentos referentes ao protótipo com sua nova versão.
- [x] Atualizar a wiki, mantendo as versões anteriores para comparação.

**Critérios de aceitação:**
- [x] Protótipo de papel feito.
- [x] Wiki foi atualizada mantendo o versionamento.

**Comment by iurisevero** [comment]
**Tela Inicial**

<kbd>
    <img alt="Tela Inicial" src="https://raw.githubusercontent.com/Interacao-Humano-Computador/2019.2-OLX/master/img/prototipo_de_baixa_fidelidade/main_page.png">
</kbd>

<br>

**Tela de Cadastro**

<kbd>
    <img alt="Tela de Cadastro" src="https://raw.githubusercontent.com/Interacao-Humano-Computador/2019.2-OLX/master/img/prototipo_de_baixa_fidelidade/tela_cadastro.png">
</kbd>

<br>

**Tela de Login**

<kbd>
    <img alt="Tela de Login" src="https://raw.githubusercontent.com/Interacao-Humano-Computador/2019.2-OLX/master/img/prototipo_de_baixa_fidelidade/tela_login.png">
</kbd>

<br>

**Meus Anúncios**

<kbd>
    <img alt="Meus Anúncios" src="https://raw.githubusercontent.com/Interacao-Humano-Computador/2019.2-OLX/master/img/prototipo_de_baixa_fidelidade/meus_anuncios.png">
</kbd>

<br>

**Tela de criação de Anuncios (Anunciar">**

<kbd>
    <img alt="Tela de Anúncio" src="https://raw.githubusercontent.com/Interacao-Humano-Computador/2019.2-OLX/master/img/prototipo_de_baixa_fidelidade/tela_anunciar.png">
</kbd>

<br>

**Tela da página de Chat**

<kbd>
    <img alt="Tela do Chat" src="https://raw.githubusercontent.com/Interacao-Humano-Computador/2019.2-OLX/master/img/prototipo_de_baixa_fidelidade/tela_chat.png">
</kbd>

<br>

**Tela de visualização de um anúncio próprio**

<kbd>
    <img alt="Tela de visualização de um anúncio próprio" src="https://raw.githubusercontent.com/Interacao-Humano-Computador/2019.2-OLX/master/img/prototipo_de_baixa_fidelidade/aluguel_apt_editavel.png">
</kbd>

<br>

**Tela de um anúncio de terceiros**

<kbd>
    <img alt="Tela de um anúncio de terceiros" src="https://raw.githubusercontent.com/Interacao-Humano-Computador/2019.2-OLX/master/img/prototipo_de_baixa_fidelidade/anuncio_moto.png">
</kbd>

<br>

**Filtro de Imóveis selecionado**

<kbd>
    <img alt="Filtro de imóveis" src="https://raw.githubusercontent.com/Interacao-Humano-Computador/2019.2-OLX/master/img/prototipo_de_baixa_fidelidade/filtro_imoveis.png">
</kbd>

<br>

**Filtro de Automóveis selecionado**

<kbd>
    <img alt="Filtro de automóveis" src="https://raw.githubusercontent.com/Interacao-Humano-Computador/2019.2-OLX/master/img/prototipo_de_baixa_fidelidade/filtro_automoveis.png">
</kbd>

<br>

**Filtro de Aparelhos tecnológicos selecionado**

<kbd>
    <img alt="Filtro de aparelhos tecnológicos" src="https://raw.githubusercontent.com/Interacao-Humano-Computador/2019.2-OLX/master/img/prototipo_de_baixa_fidelidade/filtro_aparelhos_tecnologicos.png">
</kbd>

<br>

**Tela de Busca Avançada**

<kbd>
    <img alt="Busca Avançada" src="https://raw.githubusercontent.com/Interacao-Humano-Computador/2019.2-OLX/master/img/prototipo_de_baixa_fidelidade/busca_avancada.png">
</kbd>

**Barra de Navegação após o login**

<kbd>
    <img alt="Barra de Navegação após o login" src="https://raw.githubusercontent.com/Interacao-Humano-Computador/2019.2-OLX/master/img/prototipo_de_baixa_fidelidade/navbar_pos_login.png">
</kbd>
