### ISSUE TITLE
Reestruturar storyboard

### ISSUE THREAD

**Issue by heylisten64** [Interacao-Humano-Computador/2019.2-OLX#5]
Revisar em equipe storyboard já criado para a aplicação, buscando melhorias.

**Tarefas**
- [ ] Revisar o trabalho do storyboard 

**Critérios de Aceitação**
- [ ] Storyboard redefinido: mais claro, mais objetivo e elegante para apresentação.

**Comment by juniopereirab** [comment]
De acordo com o feedback do professor no Ponto de Controle 2, é necessário que seja feito mais um storyboard sobre o caso do usuário que é comprador e vendedor.
